dromara:
  x-file-storage: #文件存储配置，不使用的情况下可以不写
    default-platform: fastdfs-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    fastdfs: # 谷歌云存储
      - platform: fastdfs-1 # 存储平台标识
        enable-storage: true  # 启用存储
        tracker-Server: 114.118.2.198:23000
        http-anti-steal-token: false
        http-secret-key: FastDFS1234567890