version: '3.8'
services:
  tracker:
    image: season/fastdfs:1.2
    restart: always
    ports:
      - "22122:22122"
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: tracker
  storage:
    image: season/fastdfs:1.2
    restart: always
    ports:
      - "23000:23000"
      - "8888:8888"
    network_mode: host
    volumes:
      - "./storage.conf:/fdfs_conf/storage.conf"
      - "./storage_base_path:/fastdfs/storage/data"
      - "./store_path0:/fastdfs/store_path"
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: storage
  nginx:
    image: season/fastdfs:1.2
    restart: always
    network_mode: host
    ports:
      - "8088:8088"
    volumes:
      - "./nginx.conf:/etc/nginx/conf/nginx.conf"
      - "./store_path0:/fastdfs/store_path"
    command: "nginx"